[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "test"
remappings = [
  "@openzeppelin/=node_modules/@openzeppelin/",
  "@gelatonetwork/relay-context/=node_modules/@gelatonetwork/relay-context/",
  "@gelatonetwork/relay-sdk/=node_modules/@gelatonetwork/relay-sdk/"
]
gas_reports = ["*"]
via_ir = true
